# Generated by Django 4.0.3 on 2022-05-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ID_no',
            new_name='id_no',
        ),
    ]
