# Generated by Django 4.0.3 on 2022-05-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0002_profile_desig_profile_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desig',
            field=models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('students', 'students')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_no',
            field=models.IntegerField(),
        ),
    ]
