# Generated by Django 4.0.3 on 2022-05-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0003_alter_profile_desig_alter_profile_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_no',
            field=models.TextField(),
        ),
    ]
