# Generated by Django 4.0.3 on 2022-05-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0004_attandance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandance',
            name='date',
            field=models.CharField(default='', max_length=70),
        ),
    ]
