# Generated by Django 4.0.3 on 2022-05-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0005_attandance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_details',
            name='no_of_classes',
            field=models.CharField(blank=True, default='1', max_length=70, null=True),
        ),
    ]
