# Generated by Django 4.0.3 on 2022-05-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0006_alter_profile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_no',
            field=models.CharField(default='0', max_length=70),
        ),
    ]
