# Generated by Django 4.0.3 on 2022-05-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0007_alter_profile_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/<django.db.models.fields.CharField>.jpg'),
        ),
    ]
