# Generated by Django 4.0.3 on 2022-05-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0010_student_rename_department_profile_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='user',
        ),
    ]
