# Generated by Django 4.0.3 on 2022-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0011_rename_name_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
        migrations.AddField(
            model_name='profile',
            name='classa',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
