# Generated by Django 4.0.3 on 2022-05-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0012_delete_student_profile_classa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Designation',
            field=models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('students', 'students')], default='admin', max_length=20),
        ),
    ]
