# Generated by Django 4.0.3 on 2022-05-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0013_alter_profile_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classa',
        ),
    ]
