# Generated by Django 4.0.3 on 2022-05-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0014_remove_profile_classa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='ID_no',
            field=models.CharField(default='0', max_length=70, primary_key=True, serialize=False),
        ),
    ]
