# Generated by Django 4.0.3 on 2022-05-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0015_remove_profile_id_alter_profile_id_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='std_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='A', max_length=70)),
                ('branch', models.CharField(default='Ph.D', max_length=70)),
                ('staff', models.CharField(default='none', max_length=70)),
                ('subject', models.CharField(default='library', max_length=70)),
                ('semester', models.CharField(default='1', max_length=20)),
                ('hour', models.CharField(default='1', max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.CharField(default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Designation',
            field=models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('students', 'student')], default='admin', max_length=20),
        ),
    ]
