# Generated by Django 4.0.3 on 2022-05-20 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facein', '0017_remove_std_details_branch_std_details_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ID_no',
            field=models.CharField(default='0', max_length=70),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
