# Generated by Django 4.0.3 on 2022-05-20 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facein', '0018_alter_profile_id_no_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ID_no',
            field=models.CharField(default='0', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
