# Generated by Django 4.0.3 on 2022-05-20 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facein', '0020_alter_profile_id_no_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ID_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.CharField(default='0', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Designation',
            field=models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('students', 'students')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='section',
            field=models.CharField(default='A', max_length=70),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
