# Generated by Django 4.0.3 on 2022-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0021_remove_profile_id_no_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ID_no',
            field=models.CharField(default='0', max_length=70),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
