# Generated by Django 4.0.3 on 2022-05-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facein', '0022_profile_id_no_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
